data = {
	"data": [
		{
			"DBN": "01M458",
			"SchoolName": "Forsyth Satellite Academy",
			"School Type": "High School Transfer",
			"OverallScore": 45.5,
			"Overall Grade": "D",
			"Overall Rank": 40,
			"Progress Grade": "B",
			"Performance Grade": "D",
			"Environment Grade": "D",
			"College and Career Readiness Grade": "C",
			"Closing the Achievement Gap Points": 6.5,
			"Principal": "Ingrid Roberts Haynes",
			"Enrollment": 225,
			"Average English Proficiency": 2.57,
			"Average Math Proficiency": 2.31,
			"% Students with Disabilities": 0.191,
			"% Self-Contained": 0.044,
			"% Overage": 0.763,
			"% Black or Hispanic": 0.929,
			"% ELL": 0.053
		  },
		  {
			"DBN": "01M515",
			"SchoolName": "Lower East Side Preparatory High School",
			"School Type": "High School Transfer",
			"OverallScore": 85.6,
			"Overall Grade": "A",
			"Overall Rank": 3,
			"Progress Grade": "A",
			"Performance Grade": "A",
			"Environment Grade": "B",
			"College and Career Readiness Grade": "A",
			"Closing the Achievement Gap Points": 10.4,
			"Principal": "Martha Polin",
			"Enrollment": 513,
			"Average English Proficiency": 2.66,
			"Average Math Proficiency": 2.59,
			"% Students with Disabilities": 0.021,
			"% Self-Contained": 0.01,
			"% Overage": 0.821,
			"% Black or Hispanic": 0.205,
			"% ELL": 0.782
		  },
		  {
			"DBN": "01M650",
			"SchoolName": "Cascades High School",
			"School Type": "High School Transfer",
			"OverallScore": 75.4,
			"Overall Grade": "A",
			"Overall Rank": 9,
			"Progress Grade": "A",
			"Performance Grade": "A",
			"Environment Grade": "B",
			"College and Career Readiness Grade": "B",
			"Closing the Achievement Gap Points": 7.9,
			"Principal": "Paul Rotondo",
			"Enrollment": 228,
			"Average English Proficiency": 2.68,
			"Average Math Proficiency": 2.66,
			"% Students with Disabilities": 0.083,
			"% Self-Contained": 0.022,
			"% Overage": 0.457,
			"% Black or Hispanic": 0.947,
			"% ELL": 0.035
		  },
		  {
			"DBN": "02M313",
			"SchoolName": "James Baldwin School, The: A School for Expeditionary Learning",
			"School Type": "High School Transfer",
			"OverallScore": 65,
			"Overall Grade": "B",
			"Overall Rank": 22,
			"Progress Grade": "B",
			"Performance Grade": "A",
			"Environment Grade": "C",
			"College and Career Readiness Grade": "A",
			"Closing the Achievement Gap Points": 7.4,
			"Principal": "Christine Olson",
			"Enrollment": 254,
			"Average English Proficiency": 2.63,
			"Average Math Proficiency": 2.63,
			"% Students with Disabilities": 0.189,
			"% Self-Contained": 0.035,
			"% Overage": 0.28,
			"% Black or Hispanic": 0.894,
			"% ELL": 0.059
		  },
		  {
			"DBN": "02M394",
			"SchoolName": "EMMA LAZARUS HIGH SCHOOL",
			"School Type": "High School Transfer",
			"OverallScore": "",
			"Overall Grade": "",
			"Overall Rank": "",
			"Progress Grade": "",
			"Performance Grade": "",
			"Environment Grade": "",
			"College and Career Readiness Grade": "",
			"Closing the Achievement Gap Points": "",
			"Principal": "Melody Kellogg",
			"Enrollment": 245,
			"Average English Proficiency": 1.95,
			"Average Math Proficiency": 2.51,
			"% Students with Disabilities": 0,
			"% Self-Contained": 0,
			"% Overage": 0.718,
			"% Black or Hispanic": 0.327,
			"% ELL": 0.853
		  },
		  {
			"DBN": "02M432",
			"SchoolName": "MURRAY HILL ACADEMY",
			"School Type": "High School Transfer",
			"OverallScore": "",
			"Overall Grade": "",
			"Overall Rank": "",
			"Progress Grade": "",
			"Performance Grade": "",
			"Environment Grade": "",
			"College and Career Readiness Grade": "",
			"Closing the Achievement Gap Points": "",
			"Principal": "Anita Manninen Felix",
			"Enrollment": 286,
			"Average English Proficiency": 2.59,
			"Average Math Proficiency": 2.69,
			"% Students with Disabilities": 0.259,
			"% Self-Contained": 0.101,
			"% Overage": 0.14,
			"% Black or Hispanic": 0.878,
			"% ELL": 0.077
		  },
		  {
			"DBN": "02M544",
			"SchoolName": "Independence High School",
			"School Type": "High School Transfer",
			"OverallScore": 48.7,
			"Overall Grade": "C",
			"Overall Rank": 36,
			"Progress Grade": "C",
			"Performance Grade": "C",
			"Environment Grade": "A",
			"College and Career Readiness Grade": "B",
			"Closing the Achievement Gap Points": 7.1,
			"Principal": "Ron Smolkin",
			"Enrollment": 388,
			"Average English Proficiency": 2.53,
			"Average Math Proficiency": 2.38,
			"% Students with Disabilities": 0.18,
			"% Self-Contained": 0.041,
			"% Overage": 0.592,
			"% Black or Hispanic": 0.936,
			"% ELL": 0.059
		  },
		  {
			"DBN": "02M550",
			"SchoolName": "Liberty High School Academy for Newcomers",
			"School Type": "High School Transfer",
			"OverallScore": 85.7,
			"Overall Grade": "A",
			"Overall Rank": 2,
			"Progress Grade": "A",
			"Performance Grade": "A",
			"Environment Grade": "D",
			"College and Career Readiness Grade": "A",
			"Closing the Achievement Gap Points": 10.6,
			"Principal": "Melodee Khristan",
			"Enrollment": 383,
			"Average English Proficiency": 1.77,
			"Average Math Proficiency": 2.3,
			"% Students with Disabilities": 0.029,
			"% Self-Contained": 0.005,
			"% Overage": 0.56,
			"% Black or Hispanic": 0.655,
			"% ELL": 0.911
		  },
		  {
			"DBN": "02M560",
			"SchoolName": "High School M560 - City As School",
			"School Type": "High School Transfer",
			"OverallScore": 48,
			"Overall Grade": "C",
			"Overall Rank": 37,
			"Progress Grade": "F",
			"Performance Grade": "B",
			"Environment Grade": "B",
			"College and Career Readiness Grade": "B",
			"Closing the Achievement Gap Points": 7.9,
			"Principal": "Alan Cheng",
			"Enrollment": 631,
			"Average English Proficiency": 2.79,
			"Average Math Proficiency": 2.61,
			"% Students with Disabilities": 0.135,
			"% Self-Contained": 0.013,
			"% Overage": 0.339,
			"% Black or Hispanic": 0.826,
			"% ELL": 0.021
		  },
		  {
			"DBN": "02M565",
			"SchoolName": "Urban Academy Laboratory High School",
			"School Type": "High School Transfer",
			"OverallScore": 68.8,
			"Overall Grade": "A",
			"Overall Rank": 15,
			"Progress Grade": "A",
			"Performance Grade": "B",
			"Environment Grade": "A",
			"College and Career Readiness Grade": "A",
			"Closing the Achievement Gap Points": 5.5,
			"Principal": "Herb Mack",
			"Enrollment": 160,
			"Average English Proficiency": 3.05,
			"Average Math Proficiency": 2.89,
			"% Students with Disabilities": 0.1,
			"% Self-Contained": 0.006,
			"% Overage": 0.226,
			"% Black or Hispanic": 0.688,
			"% ELL": 0.019
		  }
	]
}